FROM tomcat:8.5 AS tomcat_base

#MAINTAINER hello@gritfy.com

RUN mkdir /opt/tomcat/

#WORKDIR /opt/tomcat
#RUN curl -O https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz
#RUN curl -O https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.87/bin/apache-tomcat-8.5.87.tar.gz
#RUN tar xvfz apache*.tar.gz
#RUN mv apache-tomcat-8.5.87/* /opt/tomcat/.
#RUN yum -y install java
#RUN java -version

WORKDIR /usr/local/tomcat/webapps
RUN curl -O -L https://github.com/AKSarav/SampleWebApp/raw/master/dist/SampleWebApp.war


FROM tomcat_base AS app1
RUN mv SampleWebApp.war app1.war

FROM tomcat_base AS app2
RUN mv SampleWebApp.war app2.war


#EXPOSE 8080


#CMD ["catalina.sh", "run"]
